# Generated by Django 4.1.3 on 2023-04-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesages', '0002_alter_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-datetime_send',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
